on:  
 push:  
    branches: [ master ]  
 pull_request:  
    branches: [ master ]  

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Sql
      run: env
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/sql-action@v2
      with:  
        server-name: 'tcp:geofreyganot.database.windows.net,1433'  
        connection-string: 'Server=tcp:geofreyganot.database.windows.net,1433;Initial Catalog=SampleDatabaseForDeployment;Persist Security Info=False;User ID=geofreyganot;Password=Geofrey@123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
        path: './SampleDatabaseForDeployment.dacpac'
        action: publish
    - run: |
        az webapp list --query "[?state=='Running']"
