name: Azure App Service - dotnetthoughts(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - name: Azure SQL Deploy
      uses: Azure/sql-action@v1
      with:
        # Name of the Azure SQL Server name, like Fabrikam.database.windows.net.
        server-name: tcp:geofreyganot.database.windows.net,1433
        # The connection string, including authentication information, for the Azure SQL Server database.
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        # Path to SQL script file to deploy
        sql-file: ${{env.DOTNET_ROOT}}/sql/sql-script.sql

