on:  
 push:  
    branches: [ master ]  
 pull_request:  
    branches: [ master ]  
  
  
jobs:  
  deploy:
    runs-on: self-hosted-ubuntu
    steps:
      - uses: elstudio/action-install-azure-cli@v1
      - uses: azure/webapps-deploy@v2
  build:  
   runs-on: windows-latest  
   steps:  
    - uses: actions/checkout@v1  
    - uses: azure/login@v1  
      with:  
        creds: ${<!-- -->{ secrets.AZURE_CREDENTIALS }}  
      
    - uses: azure/sql-action@v1  
      with:  
       server-name: 'geofreyganot.database.windows.net'  
       connection-string: ${<!-- -->{ secrets.AZURE_SQL_CONNECTION_STRING }}  
       sql-file: './run_sql.sql'  
    # Azure logout   
    - name: logout  
      run: |  
           az logout
