on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/sql-action@v1  
      with:  
        server-name: 'tcp:geofreyganot.database.windows.net,1433'  
        connection-string: ${<!-- -->{ secrets.AZURE_SQL_CONNECTION_STRING }}  
        sql-file: './run_sql.sql'      
    - run: |
        az webapp list --query "[?state=='Running']"
